=== UO278036/web-test/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tipoRuta" />
				<xs:element ref="medioDetransporte" />
				<xs:element minOccurs="0" maxOccurs="1" ref="fechaDeinicio" />
				<xs:element minOccurs="0" maxOccurs="1" ref="horaDeinicio" />
				<xs:element ref="duracion" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcion" />
				<xs:element ref="personasAdecuadas" />
				<xs:element ref="InicioRutaLugar" />
				<xs:element ref="InicioRutaDireccion" />
				<xs:element ref="coordenadas" />
				<xs:element ref="referenciasYBibliografias" />
				<xs:element ref="recomendacioRuta" />
				<xs:element ref="hitos" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="tipoRuta" type="xs:string" />
	<xs:element name="medioDetransporte" type="xs:string" />
	<xs:element name="fechaDeinicio" type="xs:date" />
	<xs:element name="horaDeinicio" type="xs:time" />
	<xs:element name="duracion" type="xs:string" />
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="personasAdecuadas" type="xs:string" />
	<xs:element name="InicioRutaLugar" type="xs:string" />
	<xs:element name="InicioRutaDireccion" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:float" />
	<xs:element name="latitud" type="xs:float" />
	<xs:element name="altitud" type="xs:float" />
	<xs:element name="referenciasYBibliografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referenciasYBibliografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referenciasYBibliografia" type="xs:string" />
	<xs:element name="recomendacioRuta" type="puntuacion" />
	<xs:simpleType name="puntuacion">
		<xs:restriction base="xs:integer">
			<xs:maxInclusive value = "10" />
			<xs:minInclusive value = "0" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreDehito" />
				<xs:element ref="descripcionDehito" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distancia" />
				<xs:element ref="galeriaFotografia" />
				<xs:element minOccurs="0" maxOccurs="1" ref="galeriaVideo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombreDehito" type="xs:string" />
	<xs:element name="descripcionDehito" type="xs:string" />
	<xs:element name="distancia" type="xs:double" />
	<xs:element name="galeriaFotografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:attribute name ="nombre_foto" type="xs:string"/>
			<xs:attribute name ="ref_foto" type="xs:string"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="galeriaVideo">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:attribute name ="nombre_video" type="xs:string"/>
			<xs:attribute name ="ref_video" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== UO278036/web-test/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xsi:schemaLocation="http://www.uniovi.es rutas.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.uniovi.es">
   <ruta nombre = "CentroAfriacana" >
        <tipoRuta>Naturaleza</tipoRuta>
        <medioDetransporte>A pie</medioDetransporte>
        <fechaDeinicio>2023-11-25</fechaDeinicio>
        <horaDeinicio>13:00:00</horaDeinicio>

        <duracion>4 horas</duracion>
        <agencia>Viaboo</agencia>
        <descripcion> República Centroafricana es una aventura emocionante y única. Es una experiencia única que ofrece la oportunidad de descubrir algunos de los mejores paisajes y 
        culturas de la región. Sin embargo, los viajeros deben estar preparados para los retos de la carretera.</descripcion>
        <personasAdecuadas>Personas aventureras y sin miedo a la Naturaleza</personasAdecuadas>
        <InicioRutaLugar>BanguiBoda</InicioRutaLugar>
        <InicioRutaDireccion>Provincia de Bangui</InicioRutaDireccion>
        <coordenadas>
            <longitud>14.666667</longitud>
            <latitud>5.166667</latitud>
            <altitud>600</altitud>
        </coordenadas>
        <referenciasYBibliografias>
            <referenciasYBibliografia>https://viaboo.com/es/roadtrips/Africa/Central_Africa/CAR/Grandtour</referenciasYBibliografia>
            <referenciasYBibliografia>http://blog.kananga.com/ruta-kananga-abismo-verde-reserva-dzanga-shanga/</referenciasYBibliografia>
            <referenciasYBibliografia>https://es.wikiloc.com/rutas-observacion-de-fauna/23-ruta-al-bai-de-dzanga-106155356</referenciasYBibliografia>
        </referenciasYBibliografias>
        <recomendacioRuta>8</recomendacioRuta>
        <hitos>
            <hito>
                <nombreDehito>Hito sendero</nombreDehito>
                <descripcionDehito>Llegar a la cima de la montaña de Buki</descripcionDehito>
              
                <coordenadas>
                    <longitud>17.175350</longitud>
                    <latitud> 6.120614</latitud>
                    <altitud>700</altitud>
                </coordenadas>
                <distancia>2200</distancia>
                <galeriaFotografia>                
                    <fotografia ref_foto = "xml/multimediaXML/foto1.jpg" nombre_foto = "Foto Cataratas"></fotografia>
                </galeriaFotografia>
            </hito>
            <hito>
                <nombreDehito>Hito Bangalusi</nombreDehito>
                <descripcionDehito>Llegar a la cima de la montaña de Buki</descripcionDehito>
                <coordenadas>
                    <longitud>17.25</longitud>
                    <latitud>6.25</latitud>
                    <altitud>800</altitud>
                </coordenadas>
                <distancia>1500</distancia>
                <galeriaFotografia>
                    <fotografia ref_foto = "xml/multimediaXML/foto2.jpg" nombre_foto = "Foto Gorila"></fotografia>
                </galeriaFotografia>
            </hito>
            <hito>
                <nombreDehito>Hito cima cataratas</nombreDehito>
                <descripcionDehito>Llegar a la cima de la montaña de Buki</descripcionDehito>
                <coordenadas>
                    <longitud>17.212267</longitud>
                    <latitud>6.236186</latitud>
                    <altitud>605</altitud>
                </coordenadas>
                <distancia>1900</distancia>
                <galeriaFotografia>
                    <fotografia ref_foto = "xml/multimediaXML/foto3.jpg" nombre_foto = "Foto Vistas"></fotografia>
                </galeriaFotografia>
                <galeriaVideo>
                    <video ref_video = "xml/multimediaXML/vide1.mp4" nombre_video="Video del Bangalusi"></video>
                </galeriaVideo>
            </hito>
        </hitos>
    </ruta>
    <ruta nombre="RutaFaunaSavannah">
        <!-- Ruta 2 - Fauna y Paisajes de la Sabana -->
        <tipoRuta>Aventura</tipoRuta>
        <medioDetransporte>En vehículo todo terreno</medioDetransporte>
        <fechaDeinicio>2023-12-01</fechaDeinicio>
        <horaDeinicio>08:00:00</horaDeinicio>

        <duracion>7 dias</duracion>
        <agencia>Aventuras Salvajes</agencia>
        <descripcion>Embárcate en un emocionante safari por la sabana de la República Centroafricana, donde podrás admirar la impresionante fauna y los paisajes únicos.</descripcion>
        <personasAdecuadas>Amantes de la naturaleza y la observación de vida salvaje</personasAdecuadas>
        <InicioRutaLugar>Bamingui-Bangoran</InicioRutaLugar>
        <InicioRutaDireccion>Región de la Sabana</InicioRutaDireccion>
        <coordenadas>
            <longitud>18.559660</longitud>
            <latitud>4.907330</latitud>
            <altitud>375</altitud>
        </coordenadas>
        <referenciasYBibliografias>
            <referenciasYBibliografia>https://www.civitatis.com/es/jarabacoa/trekking-3-dias-pico-duarte/</referenciasYBibliografia>
            <referenciasYBibliografia>https://es.wikiloc.com/rutas/outdoor/republica-centroafricana</referenciasYBibliografia>
            <referenciasYBibliografia>https://serturista.com/republica-centroafricana/parque-nacional-de-manovo-gounda-st-floris/</referenciasYBibliografia>
        </referenciasYBibliografias>
        <recomendacioRuta>5</recomendacioRuta>
        <hitos>
            <hito>
                <nombreDehito>Bangui, República Centroafricana</nombreDehito>
                <descripcionDehito>Explora la reserva y observa la diversidad de vida salvaje</descripcionDehito>
                <coordenadas>
                    <longitud>16.958050</longitud>
                    <latitud>5.215270</latitud>
                    <altitud>700</altitud>
                </coordenadas>
                <distancia>5000</distancia>
                <galeriaFotografia>
                    <fotografia ref_foto = "xml/multimediaXML/foto4.jpg" nombre_foto = "Foto Selva"></fotografia>
                </galeriaFotografia>
            </hito>
            <hito>
                <nombreDehito>Parque Nacional de Dzanga Sangha, República Centroafricana</nombreDehito>
                <descripcionDehito>Ascenso al Monte Kaga-Bandoro para disfrutar de vistas panorámicas de la sabana</descripcionDehito>
                <coordenadas>
                    <longitud>16.224760</longitud>
                    <latitud>6.052990</latitud>
                    <altitud>800</altitud>
                </coordenadas>
                <distancia>7000</distancia>
                <galeriaFotografia>
                    <fotografia ref_foto = "xml/multimediaXML/foto5.jpg" nombre_foto = "Foto Paisaje"></fotografia>
                </galeriaFotografia>
            </hito>
            
            <hito>
                <nombreDehito>Reserva de Fauna de Chinko, República Centroafricana</nombreDehito>
                <descripcionDehito>Disfruta de una impresionante puesta de sol en Bamingui-Bangoran al final del día</descripcionDehito>
                <coordenadas>
                    <longitud>16.587010</longitud>
                    <latitud>6.440330</latitud>
                    <altitud>900</altitud>
                </coordenadas>
                <distancia>1000</distancia>
                <galeriaFotografia>
                    <fotografia ref_foto = "xml/multimediaXML/foto6.jpg" nombre_foto = "Foto praderas"></fotografia>
                </galeriaFotografia>
            </hito>         
        </hitos>
    </ruta>
<ruta nombre="RutaCascadasBamingui">
        <!-- Ruta 3 - Cascadas de Bamingui -->
        <tipoRuta>Naturaleza</tipoRuta>
        <medioDetransporte>A pie</medioDetransporte>
        <fechaDeinicio>2023-12-05</fechaDeinicio>
        <horaDeinicio>09:00:00</horaDeinicio>
        <duracion>3 horas</duracion>
        <agencia>ExploraNaturaleza</agencia>
        <descripcion>Descubre la belleza natural de las cascadas de Bamingui, donde el agua fluye en un entorno exuberante y tranquilo.</descripcion>
        <personasAdecuadas>Amantes de la naturaleza y excursionistas</personasAdecuadas>
        <InicioRutaLugar>Bamingui</InicioRutaLugar>
        <InicioRutaDireccion>Región de Bamingui</InicioRutaDireccion>
        <coordenadas>
            <longitud>18.559660</longitud>
            <latitud>4.907330</latitud>
            <altitud>375</altitud>
        </coordenadas>
        <referenciasYBibliografias>
            <referenciasYBibliografia>https://www.easyviajar.com/republica-centroafricana/las-cataratas-de-boali-603</referenciasYBibliografia>
            <referenciasYBibliografia>https://www.freepik.es/vector-premium/mapa-ciudad-republica-centroafricana-bangui-estilo-retro-color-dorado-esquema-mapa-vector-ilustracion_25738508.htm</referenciasYBibliografia>
            <referenciasYBibliografia>https://serturista.com/republica-centroafricana/parque-nacional-de-manovo-gounda-st-floris/</referenciasYBibliografia>
        </referenciasYBibliografias>
        <recomendacioRuta>6</recomendacioRuta>
        <hitos>
            <hito>
                <nombreDehito>Cascada principal de Bamingui</nombreDehito>
                <descripcionDehito>Contempla la majestuosidad de la cascada principal</descripcionDehito>
                <coordenadas>
                    <longitud>18.541751</longitud>
                    <latitud>4.906997</latitud>
                    <altitud>377</altitud>
                </coordenadas>
                <distancia>2000</distancia>
                <galeriaFotografia>
                    <fotografia ref_foto = "xml/multimediaXML/foto7.jpg" nombre_foto = "Foto lagunas"></fotografia>
                </galeriaFotografia>
            </hito>
            <hito>
                <nombreDehito>Sendero Escénico de Bamingui</nombreDehito>
